# Generated by Django 5.2.1 on 2025-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
